Write-Host "AerethDesignTools"
Write-Host "No external packages required."
Write-Host ""
Write-Host "Test commands:"
Write-Host "python xp_curve.py --from-level 1 --to-level 10"
Write-Host "python combat_simulator.py --player-level 15 --mob-level 15 --difficulty normal"
Write-Host "python mob_balancer.py --player-level 15 --mob-level 15 --difficulty normal"
Write-Host "python quest_reward_budget.py --level 12 --minutes 8 --quest-type story"
Write-Host "python loot_budget.py --level 20 --rarity rare"
Write-Host "python time_to_level.py --start-level 1 --end-level 15 --preset balanced"
